"""Runtime pack/unpack for schema-defined fixed-layout messages.

Same byte contract as the C header generated by tools/silschema.py:
little-endian, declared field order, no padding.
"""

from __future__ import annotations

import struct

_FMT = {
    "u8": "B", "u16": "H", "u32": "I", "u64": "Q",
    "i8": "b", "i16": "h", "i32": "i", "i64": "q",
    "f32": "f", "f64": "d",
}


class MessageType:
    def __init__(self, name: str, spec: dict):
        self.name = name
        self.field_names = [f["name"] for f in spec["fields"]]
        self._struct = struct.Struct(
            "<" + "".join(_FMT[f["type"]] for f in spec["fields"])
        )
        self.size = self._struct.size

    def pack(self, **values) -> bytes:
        return self._struct.pack(*(values[n] for n in self.field_names))

    def unpack(self, data: bytes) -> dict:
        return dict(zip(self.field_names, self._struct.unpack(data)))


def load(schemas: dict) -> dict[str, MessageType]:
    return {name: MessageType(name, spec) for name, spec in schemas.items()}
