"""Runtime pack/unpack for schema-defined fixed-layout messages.

Same byte contract as the C header generated by tools/silschema.py:
little-endian, declared field order, no padding.

A field may declare ``count`` for a fixed-size array of its element type,
laid out as ``count`` contiguous elements (no length prefix, no padding). A
``u8`` array surfaces as ``bytes``; any other element type as a ``list``.
"""

from __future__ import annotations

import struct

_FMT = {
    "u8": "B", "u16": "H", "u32": "I", "u64": "Q",
    "i8": "b", "i16": "h", "i32": "i", "i64": "q",
    "f32": "f", "f64": "d",
}


class MessageType:
    def __init__(self, name: str, spec: dict):
        self.name = name
        fields = spec["fields"]
        self.field_names = [f["name"] for f in fields]
        # Per field: how many struct values it occupies and how to convert
        # between a Python value and those values. Scalars are 1:1; arrays span
        # ``count`` values, presented as bytes (u8) or list (everything else).
        self._plans = [_field_plan(f) for f in fields]
        fmt = "<" + "".join(p.fmt for p in self._plans)
        self._struct = struct.Struct(fmt)
        self.size = self._struct.size

    def pack(self, **values) -> bytes:
        flat: list = []
        for name, plan in zip(self.field_names, self._plans):
            plan.spread(values[name], flat)
        return self._struct.pack(*flat)

    def unpack(self, data: bytes) -> dict:
        flat = self._struct.unpack(data)
        out: dict = {}
        i = 0
        for name, plan in zip(self.field_names, self._plans):
            out[name], i = plan.gather(flat, i)
        return out


class _Scalar:
    __slots__ = ("fmt",)

    def __init__(self, elem_fmt: str):
        self.fmt = elem_fmt

    def spread(self, value, flat: list) -> None:
        flat.append(value)

    def gather(self, flat, i: int):
        return flat[i], i + 1


class _ByteArray:
    """A ``u8`` array: one ``count``-length ``bytes`` value ('Ns' in struct)."""

    __slots__ = ("fmt", "_count")

    def __init__(self, count: int):
        self.fmt = f"{count}s"
        self._count = count

    def spread(self, value, flat: list) -> None:
        # struct's 'Ns' silently NUL-pads short and truncates long input, which
        # would corrupt the payload rather than reject it — check length so a
        # wrong-size blob fails like a wrong-length list does.
        if len(value) != self._count:
            raise struct.error(
                f"array field expects {self._count} bytes, got {len(value)}"
            )
        flat.append(value)

    def gather(self, flat, i: int):
        return flat[i], i + 1


class _List:
    """A non-u8 array: ``count`` separate struct values, presented as a list."""

    __slots__ = ("fmt", "_count")

    def __init__(self, elem_fmt: str, count: int):
        self.fmt = f"{count}{elem_fmt}"
        self._count = count

    def spread(self, value, flat: list) -> None:
        if len(value) != self._count:
            raise struct.error(
                f"array field expects {self._count} elements, got {len(value)}"
            )
        flat.extend(value)

    def gather(self, flat, i: int):
        return list(flat[i : i + self._count]), i + self._count


def _field_plan(field: dict):
    elem_fmt = _FMT[field["type"]]
    count = field.get("count")
    if count is None:
        return _Scalar(elem_fmt)
    if field["type"] == "u8":
        return _ByteArray(count)
    return _List(elem_fmt, count)


def load(schemas: dict) -> dict[str, MessageType]:
    return {name: MessageType(name, spec) for name, spec in schemas.items()}
