"""OSI edge participants of the OSMP qualification bundles (issue #233).

The Importer moves OSMP payloads as bytes and never decodes them. These two
Process participants sit at the edge of the experiment, outside SiL:

- `Decoder` decodes each `osi.SensorView` into `osi.GroundTruth` and each
  `<sensor>.SensorData` into `<sensor>.Detections`, in the Slot it receives
  them, so `sil compare` can compare every field with a reference.
- `UnparseableView` publishes a SensorView that no Protobuf parser accepts.

The OSI classes are generated by `protoc` from the `.proto` files the FMUs
were built from, and lie in `osi/` beside this file.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "osi"))

from osi_sensordata_pb2 import SensorData  # noqa: E402
from osi_sensorview_pb2 import SensorView  # noqa: E402
from sil.participant import ParticipantFailure, StepParticipant  # noqa: E402

VIEW = "osi.SensorView"
DETECTION_FLOATS = ("x", "y", "z", "yaw", "pitch", "roll",
                    "existence_probability", "length", "width", "height")
# A truncated varint: every byte continues it, and the payload ends.
UNPARSEABLE = b"\xff" * 8


def _padded(values: list, count: int, zero) -> list:
    if len(values) > count:
        raise ParticipantFailure(f"{len(values)} objects for {count} slots")
    return values + [zero] * (count - len(values))


def _payload(fields: dict) -> bytes:
    return bytes(fields["payload"][:fields["payload_length"]])


def _parsed(message, data: bytes, channel: str):
    try:
        message.ParseFromString(data)
    except Exception as error:  # noqa: BLE001 — protobuf raises DecodeError or its base
        raise ParticipantFailure(f"{channel}: {len(data)} bytes are no OSI message: {error}")
    return message


def ground_truth(data: bytes, slots: int) -> dict:
    view = _parsed(SensorView(), data, VIEW)
    truth = view.global_ground_truth
    vehicles = list(truth.moving_object)
    return {"seconds": view.timestamp.seconds, "nanos": view.timestamp.nanos,
            "host_id": truth.host_vehicle_id.value, "count": len(vehicles),
            "id": _padded([v.id.value for v in vehicles], slots, 0),
            **{axis: _padded([getattr(v.base.position, axis) for v in vehicles], slots, 0.0)
               for axis in "xyz"}}


def detections(data: bytes, slots: int, channel: str) -> dict:
    sensor = _parsed(SensorData(), data, channel)
    found = list(sensor.moving_object)
    values = {
        "ground_truth_id": [o.header.ground_truth_id[0].value for o in found],
        "tracking_id": [o.header.tracking_id.value for o in found],
        "x": [o.base.position.x for o in found],
        "y": [o.base.position.y for o in found],
        "z": [o.base.position.z for o in found],
        "yaw": [o.base.orientation.yaw for o in found],
        "pitch": [o.base.orientation.pitch for o in found],
        "roll": [o.base.orientation.roll for o in found],
        "existence_probability": [o.header.existence_probability for o in found],
        "length": [o.base.dimension.length for o in found],
        "width": [o.base.dimension.width for o in found],
        "height": [o.base.dimension.height for o in found],
    }
    return {"seconds": sensor.timestamp.seconds, "nanos": sensor.timestamp.nanos,
            "count": len(found),
            **{name: _padded(values[name], slots, 0)
               for name in ("ground_truth_id", "tracking_id")},
            **{name: _padded(values[name], slots, 0.0) for name in DETECTION_FLOATS}}


class Decoder(StepParticipant):
    """Republish each OSI payload as typed fields in the Slot it arrives in."""

    def on_init(self, init: dict) -> None:
        # The array capacities are the Manifest's, so they are read here.
        counts = {name: next(f["count"] for f in schema["fields"] if f.get("count"))
                  for name, schema in init["schemas"].items()
                  if name in ("osi.GroundTruth", "osi.Detections")}
        self._vehicles = counts.get("osi.GroundTruth")
        self._detections = counts.get("osi.Detections")

    def on_step(self, t: int, dt: int, inputs):
        outputs = []
        for message in inputs:
            data = _payload(message.data)
            if message.channel == VIEW:
                outputs.append(("osi.GroundTruth", ground_truth(data, self._vehicles)))
            else:
                sensor = message.channel.removesuffix(".SensorData")
                outputs.append((f"{sensor}.Detections",
                                detections(data, self._detections, message.channel)))
        return outputs


class UnparseableView(StepParticipant):
    """Publish a SensorView that does not parse, once per Step."""

    def on_init(self, init: dict) -> None:
        schema = init["schemas"][init["channels"][VIEW]["schema"]]
        self._capacity = next(f["count"] for f in schema["fields"] if f["name"] == "payload")

    def on_step(self, t: int, dt: int, inputs):
        payload = UNPARSEABLE + bytes(self._capacity - len(UNPARSEABLE))
        return [(VIEW, {"payload": payload, "payload_length": len(UNPARSEABLE)})]
