#!/usr/bin/env python3
"""Generate a C header with fixed-layout message structs from a schema file.

One schema file is the single typed contract: C/C++ participants use the
generated packed structs, Python uses sil.schema to pack/unpack the same
byte layout (little-endian, declared field order, no padding).
"""

import json
import sys
from pathlib import Path

C_TYPES = {
    "u8": "uint8_t", "u16": "uint16_t", "u32": "uint32_t", "u64": "uint64_t",
    "i8": "int8_t", "i16": "int16_t", "i32": "int32_t", "i64": "int64_t",
    "f32": "float", "f64": "double",
}
SIZES = {
    "u8": 1, "u16": 2, "u32": 4, "u64": 8,
    "i8": 1, "i16": 2, "i32": 4, "i64": 8, "f32": 4, "f64": 8,
}


def c_ident(schema_name: str) -> str:
    return schema_name.replace(".", "_")


def member(f: dict) -> str:
    """C struct member for a field. A `count` makes it a fixed-size array,
    laid out as contiguous elements (packed struct, no padding)."""
    decl = f"{C_TYPES[f['type']]} {f['name']}"
    count = f.get("count")
    return f"{decl}[{count}];" if count is not None else f"{decl};"


def field_bytes(f: dict) -> int:
    return SIZES[f["type"]] * f.get("count", 1)


def generate(schemas: dict) -> str:
    lines = [
        "/* Generated by silschema.py — do not edit. */",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "#pragma pack(push, 1)",
    ]
    for name in sorted(schemas):
        fields = schemas[name]["fields"]
        lines.append("")
        lines.append(f"typedef struct {c_ident(name)} {{")
        for f in fields:
            lines.append(f"  {member(f)}")
        lines.append(f"}} {c_ident(name)};")
    lines.append("")
    lines.append("#pragma pack(pop)")
    lines.append("")
    for name in sorted(schemas):
        size = sum(field_bytes(f) for f in schemas[name]["fields"])
        lines.append(
            "#ifdef __cplusplus\n"
            f"static_assert(sizeof({c_ident(name)}) == {size}, "
            f'"{name} layout must be packed");\n'
            "#endif"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit("usage: silschema.py <schema.json> <out.h>")
    schemas = json.loads(Path(sys.argv[1]).read_text())
    out = Path(sys.argv[2])
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(generate(schemas))


if __name__ == "__main__":
    main()
